version: "3.9"

services:
  postgres:
    container_name: "talana_postgres"
    image: "postgres:12.7-alpine"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: "always"

  rabbitmq:
    container_name: "talana_rabbitmq"
    image: "rabbitmq:3.8-alpine"
    expose:
      - "5672"
    ports:
      - "5672:5672"
    restart: "always"

  api:
    &api
    container_name: "talana_api"
    build: .
    depends_on:
      - "postgres"
      - "rabbitmq"

  celery:
    <<: *api
    container_name: "talana_celery"
    depends_on:
      - "rabbitmq"
      - "api"

volumes:
  postgres_data: {}
